name: S3Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:    
  lint_and_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        # 꿀팁: npm 설치 캐시를 활성화하면 다음번 빌드부터 속도가 엄청 빨라져!
        cache: 'npm'
        cache-dependency-path: './web/package-lock.json'
    
    - name: Install Dependencies
      run: npm install
      working-directory: ./web
        
    - name: Lint React Code
      run: npm run lint
      working-directory: ./web
      
    - name: Build
      run: npm run build
      working-directory: ./web
  
